<?php

return [
        ["nome"=>"Adele","alunos"=>1],
        ["nome"=>"Alicia Keys","alunos"=>1],
        ["nome"=>"André Bankoff","alunos"=>1],
        ["nome"=>"Alinne Rosa","alunos"=>1],
        ["nome"=>"André Marques","alunos"=>1],
        ["nome"=>"Alessandra Ambrosio","alunos"=>1],
        ["nome"=>"Ana Furtado","alunos"=>1],
        ["nome"=>"Ana Paula Araújo","alunos"=>1],
        ["nome"=>"Ariana Grande","alunos"=>1],
        ["nome"=>"Ana Paula Arósio","alunos"=>1],
        ["nome"=>"Arthur Aguiar","alunos"=>1],
        ["nome"=>"Aryane Steinkopf","alunos"=>1],
        ["nome"=>"Novela Alto Astral","alunos"=>1],
        ["nome"=>"Armando Babaioff","alunos"=>2],
        ["nome"=>"Aracy Balabanian","alunos"=>3],
        ["nome"=>"Aline BarrosAdriana Birolli","alunos"=>1],
        ["nome"=>"Alexandre Borges","alunos"=>1],
        ["nome"=>"Arianne Botelho","alunos"=>1],
        ["nome"=>"Ana Maria Braga","alunos"=>1],
        ["nome"=>"Antonio Calloni","alunos"=>1],
        ["nome"=>"Ana Carolina","alunos"=>1],
        ["nome"=>"Allyson Castro","alunos"=>1],
        ["nome"=>"Ana Flávia Cavalcanti","alunos"=>1],
        ["nome"=>"Arlindo Cruz","alunos"=>1],
        ["nome"=>"Amanda de Godoi","alunos"=>1],
        ["nome"=>"Wister","alunos"=>1],
        
];